site_name: Bourges
theme:
  name: material
  logo : F5xJkAnWYAAG7eY.jpeg
  language: fr
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
